---
- name: update name server entry on local host
  hosts: localhost
  vars: 
    car_model: "BMW M3"
    country_name: USA
    title: "Systems Engineer"
  
  tasks:
    - name: Print my car model
      command:  echo " My car model is {{car_model }}"

    - name: Print my country
      command: echo " I live in the {{ country_name}}"

    - name:  Print m y title
      command: echo " I work as a {{ title }}"
