---
- name: Print list of fruits
  hosts: localhost
  vars:
    fruits:
      - Apple
      - Bannana
      - Grapes
      - Oranges
  tasks:
    - debug: msg="{{ item }}"
      with_items: '{{ fruits }}'
