---
- hosts: web
  gather_facts: false

  vars:
    pack_name: nagios
#    serv_name: httpd
  tasks:
    - name: Install { { pack_name }}
      yum:  pkg={{ pack_name }} state=installed
      become: yes
      register: output

    - debug: var=output

    - name: Print Successful message
      debug: msg="Installation is successful"
      when: output is succeeded

